import type { Case } from '@/types'

export const mockCases: Case[] = [
  {
    id: '1',
    tipo: 'texto',
    paciente: 'M.S., 58 anos',
    condicao: 'Hipertensão arterial',
    depoimento:
      'Com o acompanhamento do Dr. Rodrigo, consegui controlar minha pressão sem abrir mão da minha rotina.',
    video_url: null,
    foto_url: null,
    destaque: true,
    ativo: true,
    ordem: 1,
    created_at: '2026-06-01T12:00:00Z',
  },
  {
    id: '2',
    tipo: 'video',
    paciente: 'J.A., 47 anos',
    condicao: 'Check-up cardiometabólico',
    depoimento: 'Depoimento em vídeo sobre a mudança de hábitos após o check-up.',
    video_url: null,
    foto_url: null,
    destaque: true,
    ativo: true,
    ordem: 2,
    created_at: '2026-05-20T12:00:00Z',
  },
  {
    id: '3',
    tipo: 'texto',
    paciente: 'R.P., 63 anos',
    condicao: 'Pós-operatório cardíaco',
    depoimento: 'Atendimento humano, atencioso e extremamente competente. Recomendo de olhos fechados.',
    video_url: null,
    foto_url: null,
    destaque: true,
    ativo: true,
    ordem: 3,
    created_at: '2026-05-10T12:00:00Z',
  },
  {
    id: '4',
    tipo: 'texto',
    paciente: 'A.C., 52 anos',
    condicao: 'Colesterol elevado',
    depoimento: 'A abordagem integrativa mudou minha relação com a alimentação. Meus exames melhoraram muito.',
    video_url: null,
    foto_url: null,
    destaque: false,
    ativo: true,
    ordem: 4,
    created_at: '2026-04-28T12:00:00Z',
  },
  {
    id: '5',
    tipo: 'video',
    paciente: 'F.O., 61 anos',
    condicao: 'Arritmia cardíaca',
    depoimento: 'Depoimento em vídeo sobre o diagnóstico e tratamento da arritmia.',
    video_url: null,
    foto_url: null,
    destaque: false,
    ativo: true,
    ordem: 5,
    created_at: '2026-04-15T12:00:00Z',
  },
  {
    id: '6',
    tipo: 'texto',
    paciente: 'L.F., 39 anos',
    condicao: 'Prevenção cardiovascular',
    depoimento: 'Comecei o acompanhamento por prevenção e hoje tenho muito mais consciência sobre minha saúde.',
    video_url: null,
    foto_url: null,
    destaque: false,
    ativo: true,
    ordem: 6,
    created_at: '2026-03-30T12:00:00Z',
  },
  {
    id: '7',
    tipo: 'texto',
    paciente: 'V.M., 55 anos',
    condicao: 'Diabetes tipo 2',
    depoimento: 'O olhar cardiometabólico ajudou a controlar minha glicemia e minha pressão ao mesmo tempo.',
    video_url: null,
    foto_url: null,
    destaque: false,
    ativo: true,
    ordem: 7,
    created_at: '2026-03-12T12:00:00Z',
  },
  {
    id: '8',
    tipo: 'video',
    paciente: 'S.T., 44 anos',
    condicao: 'Ansiedade e palpitações',
    depoimento: 'Depoimento em vídeo sobre o cuidado integrado entre coração e bem-estar emocional.',
    video_url: null,
    foto_url: null,
    destaque: false,
    ativo: true,
    ordem: 8,
    created_at: '2026-02-22T12:00:00Z',
  },
]
